//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Emanet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Emanet()
        {
            this.Ceza = new HashSet<Ceza>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage = "Boþ Geçilemez!")]
        public int KitapId { get; set; }
        [Required(ErrorMessage = "Boþ Geçilemez!")]
        public int UyeId { get; set; }
        [Required(ErrorMessage = "Boþ Geçilemez!")]
        public int PersonelId { get; set; }
        [Required(ErrorMessage = "Boþ Geçilemez!")]
        public System.DateTime AlisTarihi { get; set; }
        [Required(ErrorMessage = "Boþ Geçilemez!")]
        public System.DateTime IadeTarihi { get; set; }
        public Nullable<bool> IslemDurum { get; set; }
        public Nullable<System.DateTime> TeslimTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ceza> Ceza { get; set; }
        public virtual Kitap Kitap { get; set; }
        public virtual Personel Personel { get; set; }
        public virtual Uye Uye { get; set; }
    }
}
