//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kitap()
        {
            this.Durum = true;
            this.Emanet = new HashSet<Emanet>();
        }
    
        public int Id { get; set; }
        public string Adi { get; set; }
        public int KategoriId { get; set; }
        public int YazarId { get; set; }
        public string BasimYili { get; set; }
        public string Yayinevi { get; set; }
        public string SayfaSayisi { get; set; }
        public bool Durum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emanet> Emanet { get; set; }
        public virtual Kategori Kategori { get; set; }
        public virtual Yazar Yazar { get; set; }
    }
}
