//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Uye
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Uye()
        {
            this.Ceza = new HashSet<Ceza>();
            this.Emanet = new HashSet<Emanet>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage ="Boþ Geçilemez!")]
        public string Adi { get; set; }
        [Required(ErrorMessage = "Boþ Geçilemez!")]
        public string Soyadi { get; set; }
        [Required(ErrorMessage = "Boþ Geçilemez!")]
        public string EMail { get; set; }
        [Required(ErrorMessage = "Boþ Geçilemez!")]
        public string KullaniciAdi { get; set; }
        [Required(ErrorMessage = "Boþ Geçilemez!")]
        public string Sifre { get; set; }
        [Required(ErrorMessage = "Boþ Geçilemez!")]
        public string Fotograf { get; set; }
        [Required(ErrorMessage = "Boþ Geçilemez!")]
        public string Telefon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ceza> Ceza { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emanet> Emanet { get; set; }
    }
}
